Декоративные элементы на главной странице
htmlacademy-htmlcss/2002553-sedona-33 pull request #9
Opened 2022-02-23 16:03 UTC by Andreeva-Maria

2022-02-26 14:36 UTC, olesia-sev requested changes
1. В консоли ошибки насчет отсутствия шрифтов. Проверь, пожалуйста, что не так
<img width="506" alt="image" src="https://user-images.githubusercontent.com/31774506/155846799-89bb48fa-f631-4ab3-8b3b-b2ad2cce6bd8.png">

2. Есть ошибки по пиксель перфект
<img width="315" alt="image" src="https://user-images.githubusercontent.com/31774506/155846911-62f9b51d-69c2-444c-ac42-fc0d57925ca7.png">

<img width="209" alt="image" src="https://user-images.githubusercontent.com/31774506/155846926-d548c1db-f855-4b8e-8e4e-6b4a697ea543.png">

<img width="253" alt="image" src="https://user-images.githubusercontent.com/31774506/155846935-dad7fbdb-4bd8-4257-a397-764ea9bdf09a.png">

<img width="153" alt="image" src="https://user-images.githubusercontent.com/31774506/155846947-e772bec9-1ee5-4a70-bef7-2afc2b4e161b.png">

<img width="647" alt="image" src="https://user-images.githubusercontent.com/31774506/155846957-131774dc-2269-451d-a706-f1d626940131.png">

2022-02-26 14:36 UTC, olesia-sev commented on index.html
> +            <a class="navigation-link navigation-link-current" href="#">Главная</a>
Нужно убрать хреф у текущей страницы. на главной у "Главная", в каталоге у "Гостиницы". И внести изменения в стили, чтобы ховер эффект и эффект при нажатии (:active) на активные ссылки (с классом navigation-link-current) не применялся.

2022-02-26 14:36 UTC, olesia-sev commented on styles/styles.css
> +    opacity: 0.3;
Сейчас цвет у иконок не меняется. Нужно в svg файле у path (или svg) написать
```
fill="currentColor"
```
в стилях у .navigation-icon удалить fill

currentColor будет принимать значение color элемента или его родителя, т.к. color это наследуемое свойство.

2022-02-26 14:36 UTC, olesia-sev commented on styles/styles.css
> +    opacity: 0.3;
Не нашла этот элемент
<img width="56" alt="image" src="https://user-images.githubusercontent.com/31774506/155846149-72881ac0-f4c0-43fc-9b8f-0ff0b8fd543d.png">

2022-02-26 14:36 UTC, olesia-sev commented on styles/styles.css
> +    border: none;
1. у инпута неверный font-family 
 <img width="290" alt="image" src="https://user-images.githubusercontent.com/31774506/155846469-4d6f5f21-8060-40f6-a1d3-cc910b7f368b.png">

2. неверный цвет у плейсхолдера. Для того, чтобы поменять цвет задай его псевдоэлементу .field::placeholder

2022-02-26 14:36 UTC, olesia-sev commented on styles/styles.css
> +  }
Надо перенести ховер с свг на ссылку footer-social-link, т.к. интерактивный элемент это именно ссылка, а не свг.
При этом цвет иконке можно менять с помощью currentColor, как я писала в комментарии выше.

2022-02-26 14:36 UTC, olesia-sev commented on styles/styles.css
> +  }
Это не нужно, фокус как и ховер надо применить к ссылке footer-social-link

2022-02-26 14:36 UTC, olesia-sev commented on styles/styles.css
>    }
Тоже перенести к footer-social-link

2022-02-26 14:36 UTC, olesia-sev commented on styles/styles.css
> +    fill: rgba(117, 98, 87, 0.3);
Не меняется цвет иконки при фокусе на ссылке 
<img width="176" alt="image" src="https://user-images.githubusercontent.com/31774506/155846724-bd92bf32-0628-446b-8836-0ebc6f22cbe6.png">

Также перенести все стили на hover, active, focus на ссылку logo-htmlacademy-item вместо иконки navigation-logo-htmlacademy

2022-02-26 14:39 UTC, olesia-sev commented
Отсутствует этот декоративный элемент
<img width="676" alt="image" src="https://user-images.githubusercontent.com/31774506/155847129-b14e45f3-e9cf-4399-99eb-25b1cba0aab8.png">

2022-02-27 21:18 UTC, Andreeva-Maria commented on styles/styles.css
> +  }
почему? я еще раз просмотрела лайв и как я поняла, цвет меняют у свг
если сделать, как ты написала, у меня ничего не работает
либо я не понимаю, как все исправить

2022-03-01 19:34 UTC, olesia-sev reviewed
Это уведомление о кол-ве должно быть сверстано, т.к. цифра может меняться.
<img width="85" alt="image" src="https://user-images.githubusercontent.com/31774506/156234679-a1be1250-4f5a-4bd7-99a9-7056487ac957.png">

2022-03-01 19:34 UTC, olesia-sev commented on styles/styles.css
> +    background-repeat: no-repeat, no-repeat;
Если значения повторяются, можно один раз писать `background-repeat: no-repeat;`

2022-03-01 19:36 UTC, merged

2022-03-01 19:46 UTC, olesia-sev commented
Ошибка со шрифтами осталась. Они не найдены из-за неправильных путей к файлам.
Надо так `url("../fonts/ptsans-400.woff2")`
У тебя так `url("fonts/ptsans-400.woff2")`
Обсудим, если непонятно что такое ../